INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('SteelSeries', 'Klaviatūra', null, '...',     '2023-01-11 13:23:44');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('KeySonic', 'Pele', true, 'Veca pele ir neērta lietošanā',   '2022-11-11 14:21:44');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('HP', 'Austiņas', false, 'Austiņas slikti atveido skaņu',    '2022-12-06 18:10:04');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('SteelSeries', 'Procesors', null, 'Spēcīgāks procesors var nodrošināt ātrāku datu apstrādi',     '2023-02-06 16:14:04');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('Logitech', 'Dators', true, null,    '2023-01-18 18:02:16');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('Razer', 'Austiņas', null, 'Jaunās austiņas nodrošinās ērtāku pieredzi.',    '2023-03-03 11:00:02');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('SteelSeries', 'Klaviatūra', false, '...',   '2023-01-01 10:10:56');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('Dell', 'Dators', null, 'Veca korpusa dators ir bojāts',     '2022-12-24 16:18:17');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('Microsoft', 'Procesors', true, '...',   '2022-12-17 08:15:04');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('Logitech', 'Pele', true, 'Jauna pele var uzlabot darba efektivitāti,',  '2023-02-04 09:08:07');
INSERT INTO pc_equipment (model, type, status, comment, created_date) VALUES ('A4Tech', 'Grafiska planšete', false, 'Nepieciešama darbam',     '2022-12-06 15:40:04');
